### ISSUE TITLE
REPNE prefix not handled

### ISSUE THREAD

**Issue by mmozeiko** [cmuratori/computer_enhance#10]
[repne.binary.txt](https://github.com/cmuratori/computer_enhance/files/11023817/repne.binary.txt)

```
$ sim86_clang_debug.exe repne.binary.txt
; repne.binary.txt disassembly:
bits 16
rep cmpsb
rep scasb
rep cmpsw
rep scasw
rep cmpsb
rep scasb
rep movsw
rep cmpsw
rep scasw
```

```
$ ndisasm.exe repne.binary.txt
00000000  F3A6              repe cmpsb
00000002  F3AE              repe scasb
00000004  F3A7              repe cmpsw
00000006  F3AF              repe scasw
00000008  F2A6              repne cmpsb
0000000A  F2AE              repne scasb
0000000C  F2A5              repne movsw
0000000E  F2A7              repne cmpsw
00000010  F2AF              repne scasw
```

REPE is same as REP for cmps/scas instruction.

Basically movs/stos/lods use REP prefix.
cmps/scas use REPE/REPZ (which has same encoding as REP) or REPNE/REPNZ.

**Comment by cmuratori** [comment]
I fixed this in my local version, Martins, but I was not planning on updating to the github here until after the sim section. Is this something that is causing problems for you at the moment? If so, I can go ahead and merge just the (small) changes that add proper printout for this (we were not checking the Z bit when printing REP prefixes).

\- Casey

**Comment by mmozeiko** [comment]
Oh, I don't need it at all. Just letting you know about this in case full coverage is needed/wanted by you or somebody.

**Comment by cmuratori** [comment]
I believe this should now be fixed?

\- Casey
