### ISSUE TITLE
Addresses for jumps/calls not printed out

### ISSUE THREAD

**Issue by mmozeiko** [cmuratori/computer_enhance#4]
Input bytes `E9 39 0A` produce `jmp `, but should output `jmp 0xa3c` 
Input bytes `E8 16 2E` produce `call `, but should output `call 0x2e19`

**Comment by mmozeiko** [comment]
[no_addr.binary.txt](https://github.com/cmuratori/computer_enhance/files/11008500/no_addr.binary.txt)
```
ndisasm -b 16 no_addr.binary.txt
00000000  E9390A            jmp 0xa3c
00000003  E8162E            call 0x2e1c
```

**Comment by cmuratori** [comment]
Should be fixed now! Let me know if for some reason it isn't...

\- Casey

**Comment by mmozeiko** [comment]
works now
