### ISSUE TITLE
Opcodes for text and xchg overlap

### ISSUE THREAD

**Issue by ilidemi** [cmuratori/computer_enhance#5]
`test` instruction at https://github.com/cmuratori/computer_enhance/blob/main/perfaware/sim86/sim86_instruction_table.inl#L145 should have opcode `1000010` without a `D` flag, according to table 4-31 in the manual. Table 4-25 (incorrectly) has it with a different opcode and a `D` flag so understandable how it got missed. I was playing around with code generation and noticed it getting confused distinguishing `xchg` and `test` in a table that was extracted from the .inl file.

**Comment by cmuratori** [comment]
Do you happen to have a repro ASM line for this so I can verify that it is fixed and add it to the completionist homework?

Thanks,
\- Casey

**Comment by ilidemi** [comment]
This is more of a latent bug. Instruction definitions are matched in order and `xchg` with more specific opcode goes first so it all happens to work out. If I move the definition from line 145 above the line 73, listing 0042 starts producing different results and a warning from nasm.

**Comment by cmuratori** [comment]
Since I didn't exactly have a test case, I'm not sure if I fixed this properly or not, but I changed the D flag to just be a hard-coded 0 and all previous tests passed, so it _seems_ like this is a safe change anyhow :)  Please let me know if this resolves your issue.

\- Casey

**Comment by ilidemi** [comment]
The fix looks great. Thanks!
