### ISSUE TITLE
Wrong register in listing 39 - part 1

### ISSUE THREAD

**Issue by maxtremblay** [cmuratori/computer_enhance#52]
In the homework, I believe this line of assembly is wrong. 

https://github.com/cmuratori/computer_enhance/blob/b71fef219f1f665b95427f4555f3bbac7693d4b7/perfaware/part1/listing_0039_more_movs.asm#L36

According to the 8086 manual, there is not source address calculation with the register bp since the corresponding code is instead use for Direct address.

![screenshot_10042023_22_46_04](https://github.com/cmuratori/computer_enhance/assets/52462375/64b736eb-3f4b-4455-a0e5-7f6b58b58df7)

**Comment by cmuratori** [comment]
It is legal. The assembler will encode this effective address calculation using MOD=01 with 0 as the immediate (effectively "bp + 0").

\- Casey

**Comment by maxtremblay** [comment]
Thank you for the explanation :smile:
