### ISSUE TITLE
Consider doing retf for inter-segment returns

### ISSUE THREAD

**Issue by mmozeiko** [cmuratori/computer_enhance#6]
`CA 98 44` and `C2 98 44` disassembles to same `ret 17560` instruction.
But actually first is intra-segment return, second is inter-segment return - they use different opcodes.
Typically they are written as `retn` and `retf` in asm to specify which one you want. NASM knows `retn` and `retf`.

Similarly for `CB` should be `retf`, and `C3` should be `retn`, but sim86 does `ret` for both.

**Comment by mmozeiko** [comment]
[retf.binary.txt](https://github.com/cmuratori/computer_enhance/files/11008504/retf.binary.txt)

```
$ sim86.exe retf.binary.txt
; retf.binary.txt disassembly:
bits 16
ret 17556
ret 17560
ret
ret
```

```
$ ndisasm.exe -b 16 retf.binary.txt
00000000  CA9444            retf 0x4494
00000003  C29844            ret 0x4498
00000006  CB                retf
00000007  C3                ret
```

**Comment by cmuratori** [comment]
Should be fixed now! Let me know if for some reason it isn't...

\- Casey
