### ISSUE TITLE
Bad size prefix for moving segment reg to memory

### ISSUE THREAD

**Issue by mmozeiko** [cmuratori/computer_enhance#8]
Input bytes `8C 40 3B` decodes & prints to `mov byte [bx+si+59], es` which is nonsense. Cannot move byte from segment register. There should be no `byte` prefix. Just `mov [bx+si+59], es` assembles back to `8C 40 3B` correctly.

**Comment by mmozeiko** [comment]
[byte_seg_move.binary.txt](https://github.com/cmuratori/computer_enhance/files/11008510/byte_seg_move.binary.txt)

```
$ sim86.exe byte_seg_move.binary.txt
; byte_seg_move.binary.txt disassembly:
bits 16
mov byte [bx+si+59], es
```

```
$ ndisasm.exe -b 16 byte_seg_move.binary.txt
00000000  8C403B            mov [bx+si+0x3b],es
```

**Comment by cmuratori** [comment]
Should be fixed now! Let me know if for some reason it isn't...

\- Casey
