### ISSUE TITLE
Direct intersegment jump producing incorrect output

### ISSUE THREAD

**Issue by jeng** [cmuratori/computer_enhance#9]
A direct intersegment jump cause a `jmp` and `push` to generate

Example input:
`JMP 0x5566:0x7788	;ea 66 55 88 77`

Example hexdump:
`00000000: ea88 7766 55                             ..wfU`

sim86 output:
```
bits 16
jmp 102
push bp
```

**Comment by cmuratori** [comment]
I believe this should now be fixed. Can you let me know if it resolves the issue for you?

Thanks,
\- Casey

**Comment by jeng** [comment]
Looks good on my end.
